
//--------------------------------------------------------------------------
//
// Mask Shifter STAGE   : to generate selection mask using barrel shifter.
//                      : Each STAGE shifts by 2^STAGE.
//                      : Mask generated by shifting right 1s.
//
//--------------------------------------------------------------------------

module mask_stage #(
    parameter OREG_EN       = 1,
    parameter STAGE         = 7,
    parameter DATA_W        = 7,
    parameter MASK_W        = 1 << DATA_W
)(
    input wire                  i_clk,
    input wire                  i_rst,
	input wire  [DATA_W-1:0]    i_shift,
    input wire  [MASK_W-1:0]    i_mask,

	output wire [DATA_W-1:0]    o_shift,
    output wire [MASK_W-1:0]    o_mask
);

    localparam SHIFT_DIST           = 1 << STAGE;
    localparam SHIFT_SEL            = STAGE;

    wire                        w_shift_en;
    wire    [MASK_W-1:0]        w_mask;

    assign w_shift_en = i_shift[SHIFT_SEL];
    assign w_mask = (w_shift_en) ? {{SHIFT_DIST{1'b1}}, i_mask[SHIFT_DIST +: MASK_W-SHIFT_DIST]} : i_mask;

    generate
        if (OREG_EN) begin

            reg     [DATA_W-1:0]        r_shift;
            reg     [MASK_W-1:0]        r_mask;

            assign o_shift = r_shift;
            assign o_mask = r_mask;

            always @(posedge i_clk) begin
                r_shift <= (i_rst) ? 'b0 : i_shift;
                r_mask <= (i_rst) ? 'b0 : w_mask;
            end

        end
        else begin

            assign o_shift = i_shift;
            assign o_mask = w_mask;

        end
    endgenerate
    
endmodule